name: GenoSig_MLDL
channels:
  - defaults
dependencies:
  - numpy=1.26.3
  - pandas=2.1.4
  - matplotlib=3.8.0
  - scikit-learn=1.3.0
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - keras=2.11.0

